server:
  port: 8180

spring:
  profiles:
    active: dev
  application:
    name: service-oss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accesskeyId: xxxxxx
    accesskeySecret: xxxxxx
    bucketName: antigenmhc-erciyuan