spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/er_ci_yuan_ucenter?useSSL=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: service-ucenter
  #激活环境
  profiles:
    active: dev
  #json 全局时间格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    sentinel:
      transport:
        port: 8878 #跟控制台交互的端口，随便指定一个没有使用的即可
        dashboard: localhost:8858
    nacos:
      discovery:
        server-addr: localhost:8848
  #redis
  redis:
    host: 192.168.224.129
    port: 6380
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 20 #最大连接数，默认8，负数为没有限制
        max-wait: -1 #最大阻塞等待时间，负数为没有限制，默认为-1
        max-idle: 8 #最大空闲连接数，默认为8
        min-idle: 0 #最小空闲连接数，默认为0

server:
  port: 8140

# mbp配置及其日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: cn.antigenmhc.otaku.service.manager.pojo
  mapper-locations: classpath:/xml/**.xml

member:
  #用户默认头像
  defaultAvatar: https://antigenmhc-erciyuan.oss-cn-hangzhou.aliyuncs.com/avatar/2021/01/28/thumb-1920-688669.png

redirectUri: http://ecy.gz2vip.idcfengye.com

github:
  oauth2:
    #换成自己的
    clientId: xxx
    clientSecret: xxx
    #这个是固定的
    authorizeUrl: https://github.com/login/oauth/authorize
    #github 的回调接口，可以使用内网穿透进行转发
    redirectUrl : http://localhost:9999/api/gitee/login/callback
    #这个也是固定的
    accessTokenUrl: https://github.com/login/oauth/access_token
    #这个也是固定的
    userInfoUrl: https://api.github.com/user

gitee:
  oauth2:
    clientId: xxx
    clientSecret: xxx
    redirectUrl: http://localhost:9999/api/gitee/login/callback
    authorizeUrl: https://gitee.com/oauth/authorize
    accessTokenUrl: https://gitee.com/oauth/token
    userInfoUrl: https://gitee.com/api/v5/user
